### ISSUE TITLE
Where to buy

### ISSUE THREAD

**Issue by fgnievinski** [PaulZC/NEO-M8T_GNSS_FeatherWing#1]
Hi.  Your project seems to be the best hardware option for GPS post-processed kinematic (PPK) projects.  I use the Adalogger in other projects and they are really handy.  I used to use another product from CSG Shop [here](http://www.csgshop.com/product.php?id_product=205) but it requires a laptop or smartphone to log the data, which is not very practical in the field.  Then there is Tim Everett's Pi Logger [here](http://rtkexplorer.com/pi-zero-based-gps-data-logger/), which requires some configuration and more soldering.  Your project is the closest to plug-and-play that I've found so far (I maintain a wiki list [here](https://wiki.openstreetmap.org/wiki/RTKLIB-compatible_GPS_devices#Vendors)).  Now, I'm not familiar with PCBs and EAGLE to manufacture your design.  So I thought I'd ask if you'd consider selling these boards? Or maybe you know of a shop who'd be interested in offering this kind of service?  Thanks for your time and effort. PS: I'm a land surveyor.

**Comment by PaulZC** [comment]
Hi there,
Thank you for your message.
Please contact me via the following link and we'll continue the discussion off-line:
https://www.dur.ac.uk/contactperson/?lid=1724
Best wishes,
Paul
